### ISSUE TITLE
Sorry to make an issue, but...

### ISSUE THREAD

**Issue by F1ks3r** [infernojs/babel-plugin-inferno#27]
How can i run Inferno and Inferno babel plugin in browser by just adding script tags? I know it sounds stupid, but i find it a little troublesome to build all npm packages and go through all the fuss to just try some Inferno out.

I think it would be better for new users or users who just heard of Inferno (just like me)

Again, sorry to make an issue, couldn't find any stackoverflow or any other thing of that sort.

**Comment by trueadm** [comment]
@F1ks3r Hey, I totally agree. There are a few issues though – namely, in-browser Babel compilation is really slow and can have a big impact on performance. There's nothing stopping you using Inferno in the browser with hyperscript or create-element though.

If people are happy to take the performance loss, just to try out Inferno, I could look into getting the in browser Babel compilation script working with Inferno's JSX plugin. 

What do you think?

**Comment by trueadm** [comment]
Let me know how this goes: 

https://jsfiddle.net/tL40vwqg/
