### ISSUE TITLE
Spread operator doesn't work with function call expression

### ISSUE THREAD

**Issue by titarenko** [infernojs/babel-plugin-inferno#28]
Hi! First of all: thanks for providing infrastructure for Inferno!

Unfortunately, it seems like I found an issue.

```
const { render } = Inferno

const getProps = () => ({
  className: 'red'
})

class MyComponent extends InfernoComponent {
	render() {
  	return <div {...getProps()}>Hello world</div>;
  }
}

render(
	<MyComponent />,
  document.getElementById('container')
);
```

That `div` inside `MyComponent` won't have `red` class (while if `react` babel plugin is used, [it will](https://jsfiddle.net/58p1f5c2/1/)).

Sorry, no online demonstration, since I haven't found any base setup of babel + inferno for jsfiddle (#27).

**Comment by trueadm** [comment]
@titarenko Hi @titarenko, what versions are you using of `babel-plugin-inferno` and `inferno`?

**Comment by titarenko** [comment]
"inferno": 0.7.27
"babel-plugin-inferno": 1.0.0-legacy

**Comment by trueadm** [comment]
@titarenko Can you try using Inferno 1.0-beta7 for `inferno` (and associated packages) and beta6 for `babel-plugin-inferno` and seeing if the issues exists this in the latest version?

`npm install --save inferno@beta7`
`npm install --save babel-plugin-inferno@beta6`

Note: you no longer need `inferno-dom`, all that logic has been moved into `inferno` for 1.0.

**Comment by titarenko** [comment]
@trueadm yes, with these versions it works as expected. could you please suggest me how stable is beta, and how near (or far) is final release?

**Comment by trueadm** [comment]
@titarenko 1.0 is very close, I'd say a few more weeks. In terms of stability, I'd probably say that 1.0-beta is *more* stable than 0.7.

**Comment by titarenko** [comment]
great, thanks!

**Comment by trueadm** [comment]
Happy to help :) let me know if you run into any more issues.
