### ISSUE TITLE
create test Suite for babel plugin

### ISSUE THREAD

**Issue by Havunen** [infernojs/babel-plugin-inferno#32]
Create test suite with Babel Plugin, We don't even need coverage for now. But we need tests to avoid regression bugs.

Simple mocha setup should be fine. When basis is there we can add different scenarios (spread objects. etc from history)

**Comment by hzoo** [comment]
So you can either copy what other babel plugins do (it's all the same structure, https://github.com/gaearon/babel-plugin-react-transform/blob/master/test/index.js), or use `babel-helper-plugin-test-runner` although it's only officially supported in babel as an internal module (i'm using it in babel-preset-env).

**Comment by Havunen** [comment]
There is now basic setup using mocha and istanbul for coverage.
