### ISSUE TITLE
Explore: Buble integration

### ISSUE THREAD

**Issue by lukeed** [infernojs/babel-plugin-inferno#36]
This plugin is the only reason I'm still using Babel. Perhaps that's a way to hook into Buble's JSX system?

**Comment by Havunen** [comment]
Lets create repository under infernojs organization

**Comment by lukeed** [comment]
@Havunen Yes, but I'm still not sure if this is even possible yet.

**Comment by Havunen** [comment]
we can ping rich-harris at slack regarding this. I think he will be happy to give some pointers to get started.

**Comment by TrySound** [comment]
@lukeed 
It's simple but you should use `inferno-create-element` instead. There's `jsx` option in buble which accepts a factory expression like `React.createElement` or just `createElement`.

Cons: it does not support spread props

**Comment by Havunen** [comment]
Sadly `inferno-create-element` cant achieve same performance as `createVNode` :(

**Comment by TrySound** [comment]
Is everything so bad? Then you can always fork buble as usual. :)

**Comment by lukeed** [comment]
Thanks, I'm aware but it's not what I'm after. Just trying to port an equivalent plugin to buble.

**Comment by Havunen** [comment]
Typescript plugin might be possible in next 2.3 release:
https://github.com/Microsoft/TypeScript/pull/13940

**Comment by chee** [comment]
seems to work with `inferno-hyperscript` and `buble --jsx h`

**Comment by lukeed** [comment]
@chee Yes, that's supposed to work. But most Inferno users don't use the hyperscript-plugin.

**Comment by Havunen** [comment]
Lets close this issue. We could implement it for buble If they start supporting plugins. Also new features are coming to JSX in babel7, Fe: Fragments those should be done first.
