### ISSUE TITLE
Dist version of this plugin

### ISSUE THREAD

**Issue by camerow** [infernojs/babel-plugin-inferno#37]
I'm in a requireJS environment at work and can't use npm to install this plugin, but I'd like to use Inferno. Can this repo also host a minified dist file?

**Comment by Havunen** [comment]
I will look into this tommorow.

**Comment by lukeed** [comment]
@camerow This plugin is (usually) used at compile time, not the browser. So RequireJS doesn't/wouldn't come into play here. Are you not able to install any build tools?

**Comment by camerow** [comment]
Unfortunately we have a lot of legacy code that we'd like to start slowly refactoring pieces using Inferno. In that environment we are pretty well stuck with RequireJS. A coworker got React running but we like the smaller nature of Inferno so I was hoping to get a sample environment set up for Inferno.

**Comment by lukeed** [comment]
Well again, `babel-plugin-inferno` isn't meant to be included in your bundles. It'll never make it to the browser.

Instead, it's a `devDependency` and helps produce your final RequireJS bundles.

**Comment by camerow** [comment]
Right, but `babel-plugin-inferno` makes the assumption that I am in an NPM environment with `node_modules` available. I guess I'm actually just struggling with how to configure Inferno in a RequireJS environment. I wish I could just have a `webpack.config`, `node_modules` build process but I'm trying to work with what our legacy app has.

**Comment by lukeed** [comment]
I guess I'm not fully understanding, because the RequireJS projects I've worked with in the past still used & read from `node_modules`. Compilation was never not an option.

**Comment by Havunen** [comment]
This plugin now supports ES5 environments

**Comment by Havunen** [comment]
closed are there is babel-standalone plugin to handle browser env.
