### ISSUE TITLE
import file should be specifiable

### ISSUE THREAD

**Issue by hoistedvar** [infernojs/babel-plugin-inferno#38]
At the moment the import always specifies the import source as 'inferno' there are situations such as when using rollup that this won't work as rollup does not correctly find the named exports, this is usually fixed with an import proxy file.

It should therefore be possible to set the import used by the plugin, this is a very quick fix, changing line 73 from:
`		], t.stringLiteral('inferno')));`
to
`		], t.stringLiteral(typeof opts.imports === 'string' ? opts.imports : 'inferno')));`
will allow the import module to be specified using the current `imports` option.

**Comment by Havunen** [comment]
Can you send PR for this please :)

**Comment by hoistedvar** [comment]
sorry for the delay. PR for this including documentation update created (#40)

**Comment by 4leem** [comment]
@Havunen we can close this as the PR has already been accepted and merged.
