### ISSUE TITLE
Add support for `React.Fragment`

### ISSUE THREAD

**Issue by joseprio** [infernojs/babel-plugin-inferno#56]
At the moment, the supported options for fragments are:
```
<>...</>
<Fragment>...</Fragment>
<Inferno.Fragment>...</Inferno.Fragment>
```
Projects currently using React would benefit from also supporting, `<React.Fragment>` to make the transition smoother, or being able to configure it, like `<Anything.Fragment>`.

**Comment by Havunen** [comment]
Fixed in 6.3.0
