### ISSUE TITLE
Is this safe to use with inferno 7?

### ISSUE THREAD

**Issue by caass** [infernojs/babel-plugin-inferno#57]
From [the readme](https://github.com/infernojs/babel-plugin-inferno#how-to-install):

> **Note!** Make sure babel-plugin has same **major** version as the inferno you are using!

The current version of inferno is 7.4.3, while the latest version of babel-plugin-inferno is 6.1.1. Is this line incorrect or should I avoid using babel-plugin-inferno until there's a 7.x.x release?

**Comment by caass** [comment]
Update: it seems to be working fine. I'd submit a PR for the README except it might just make more sense to release a version 7 instead and encourage folks to use that? Not sure. I'm a first time Inferno user so 😅

**Comment by Havunen** [comment]
Ah yeah, this package used to follow inferno package major version. Then later we released we can use peerDependency so that takes care of it. That comment could be removed
