### ISSUE TITLE
babel-plugin-inferno performance question

### ISSUE THREAD

**Issue by lesar** [infernojs/babel-plugin-inferno#59]
I have try to find some performance test against this plugin and inferno-hyperscript but haven't much lacky.  

I read that only jsx/Babel can be optimized but I likes to find some compare text.

Hyperscript sulution Is much more slow then jsx/Babel?  

Best regards,
Leonardo

**Comment by Havunen** [comment]
Well it highly depends, how much performance difference you would experience.
The overhead function when calling from hyperscript or createElement API is this code:
https://github.com/infernojs/inferno/blob/master/packages/inferno-hyperscript/src/index.ts

basically JSX plugin does that same thing compile time, and transforms the JSX code into `createVNode` calls which does not have this overhead. 

But anyway, if you are not building views with thousands of elements or rapidly changing components, you probably will not experience any slowness

**Comment by lesar** [comment]
Tank you very much @Havunen  

regards,  
Leonardo
