### ISSUE TITLE
Do users have to install babel-plugin-syntax-jsx?

### ISSUE THREAD

**Issue by Coachonko** [infernojs/babel-plugin-inferno#61]
According to issue #20 users should not need to install babel-plugin-syntax-jsx, however that issue was closed 6 years ago the README still says that babel-plugin-syntax-jsx must be installed.
Which is it?

**Comment by Havunen** [comment]
Hi @Coachonko , installing this plugin will install `babel-plugin-syntax-jsx` by default, because this plugin is based on that:
https://github.com/infernojs/babel-plugin-inferno/blob/master/package.json#L42
