### ISSUE TITLE
Dependency babel-eslint is deprecated

### ISSUE THREAD

**Issue by farooqkz** [infernojs/babel-plugin-inferno#62]
See this:

https://www.npmjs.com/package/babel-eslint

**Comment by Havunen** [comment]
This package has no dependencies and is up to date

**Comment by farooqkz** [comment]
hmm... what is this?

https://github.com/infernojs/babel-plugin-inferno/blob/master/package.json#L15

**Comment by Havunen** [comment]
Ah you mean that, okay but its only for development of this package not dependency when this pakcage is used. I believe that can even be removed

**Comment by Havunen** [comment]
6.6.1 released and unnecessary development dependencies have been removed
